<?php

namespace AppBundle\Repository;

/**
 * CategoryEmplacementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryEmplacementRepository extends \Doctrine\ORM\EntityRepository
{
}
